services:
  byrokrat\banking\AccountFactoryInterface:
    class: byrokrat\banking\AccountFactoryInterface

  JGI\BankAccountBundle\Validator\Constraints\BankAccountValidator:
    class: JGI\BankAccountBundle\Validator\Constraints\BankAccountValidator
    arguments:
      - '@byrokrat\banking\AccountFactoryInterface'
    tags:
      - { name: validator.constraint_validator }

